apiVersion: agent.vaka/v1alpha1
kind: ServicePolicy
services:
  {{ .ServiceName }}:
    network:
      egress:
        defaultAction: reject
        block_metadata: drop
        accept:
          - dns: {}
          - proto: tcp
            to:
{{- range .AllowedHosts }}
              - {{ . }}
{{- end }}
            ports: [443]
